### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by Madhur-Dheer** [sourav-mazumder/Data-Science-Extensions#8]
While Running the Api in Spark Shell

this command ->  val sodasDf = spark.read.format("org.apache.dsext.spark.datasource.rest.RestDataSource").options(parmg).load()

is resulting in error , the error is -:

**java.lang.NoClassDefFoundError: scala/Product$class
  at org.apache.dsext.spark.datasource.rest.RESTRelation.<init>(RestRelation.scala:41)
  at org.apache.dsext.spark.datasource.rest.RestDataSource.createRelation(RestDataSource.scala:42)
  at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:339)
  at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:240)
  at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:229)
  at scala.Option.getOrElse(Option.scala:189)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:229)
  at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:179)
  ... 47 elided
Caused by: java.lang.ClassNotFoundException: scala.Product$class
  at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
  at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
  ... 55 more**

How should i resolve this ?

**Comment by rwforest** [comment]
The scala version of scalaj-http needs to match your cluster's scala version. Pick the right version in Maven and replace that in pom.xml.
